### ISSUE TITLE
Get/ requests not working

### ISSUE THREAD

**Issue by benoitfagot** [CounterPathAPI/DesktopAPI_1.2_Sample#5]
Hi,
I'm trying to redirect users on the page containing the caller's informations, 
therefore Im trying to send the GET/ status "call" request in order to retrieve the caller's name and then use an Ajax request to get his ID in my database;

after reading your code, all i need to do is to send a GET/ status "call" and retrieve the <displayName> info from the answer

my problem is that no matter the GET/ request, I am not receiving any answers from Bria (im supposed to receive 200, 400, etc, but there are no logs), therefore none of the GET requests are working,not even bringtoFront()

the strange thing is that the websocket is CONNECTED, and that im receiving POST /statuschange messages for any events, like "call', "presence"... when i call my account with my cellphone

so it seems i can receive messages but my messages are failing to send.
Im using Bria 5.4 so its not the problem, im out of ideas to debug this
Would appreciate any help 

im attaching a screenshot 
![example](https://user-images.githubusercontent.com/36077307/52054338-787a2300-255c-11e9-8664-bbd65c3bc1e4.png)

thank you for your time

Benoit

**Comment by CounterPathAPI** [comment]
Sorry for delay.  The notifications seems to not working again on our side.

In Bria 5, have you authorized the app's access?    

Have you made any changes to the base code?  Can you post a diff?

**Comment by benoitfagot** [comment]
Hello,
I do not see where i can authorize the app's access ? 
![bria](https://user-images.githubusercontent.com/36077307/53172795-7f89d380-35e6-11e9-968c-e3752d81e368.png)

I barely changed the base code, I only added some console.logs here and there trying to debug it.
It didnt work with the base code in the first place.

here are the differences (normal police : base code,, bold police : changes made)

const userAgentString = "Bria API JavaScript Sample";
**const userAgentString = "TestApi";**

var msg = 'GET /' + ApiRequestTypes.properties[requestType].text
**var msg = 'GET/' + ApiRequestTypes.properties[requestType].text**

switch (eventType) {
    case ApiStatusEventTypes.properties[ApiStatusEventTypes.CALL].text:
**switch (eventType) {**
		**case ApiStatusEventTypes.properties[ApiStatusEventTypes.CALL].text:**
			**apiGetStatus(eventType)**;
		**case ApiStatusEventTypes.properties[ApiStatusEventTypes.PRESENCE].text:**
			**apiGetStatus("call");**
			**break;**

rest of changes are either console.log()s or code in comments

Thanks

**Comment by CounterPathAPI** [comment]
On the screenshot, there is a lighting bolt inside a note on the fourth tab.  When you click on that, iI suspect you will see a notice asking you to authorize the API access.  You also can access it through the security tab under preferences.   

The user must authorize the app for retail install.  I see you are using Bria Stretto, there is also the ability to approve API access in the provisioning file in that case

**Comment by benoitfagot** [comment]
Thank you very much, requests are working now  ! 👍

**Comment by benoitfagot** [comment]
So i have a good and bad news :
the good news is that i was able to do redirect myself from the basic bria page example to the page i wanted, so im one step away from doing what i wanted
the bad news is that when i copied the scripts to the real page on the server, i am now getting this answer in the console :

`setting status to: CONNECTED
bria_api_js_sample.js:576 Uncaught TypeError: Cannot read property 'scrollHeight' of undefined
    at appendToLog (bria_api_js_sample.js:576)
    at sendMessage (bria_api_js_sample.js:91)
    at apiGetStatus (bria_api_js_sample.js:223)
    at onConnectedToWebSocket (bria_api_js_sample.js:30)
    at WebSocket.websocket.onopen (bria_api_js_sample.js:57)
appendToLog @ bria_api_js_sample.js:576
sendMessage @ bria_api_js_sample.js:91
apiGetStatus @ bria_api_js_sample.js:223
onConnectedToWebSocket @ bria_api_js_sample.js:30
websocket.onopen @ bria_api_js_sample.js:57
monitoring2.php:123 received text data from the server: HTTP/1.1 401 Unauthorized
Transaction-ID: 
Content-Type: application/xml
Content-Length: 0`

In preferences > security, i checked "allow access every time", but it didnt work

Im honestly lost to why this isnt working, both bria example page and monitoring2 pages are located on the server in the same directory, but it seems only bria page has access to API

**Comment by benoitfagot** [comment]
Nevermind, i just had to get rid of the Appendtolog() lines in the script because the log obviously doesnt exist in my page ^^

**Comment by benoitfagot** [comment]
Hello again,

so now that the feature i wanted works on my computer, I offered some employees to experiment with it : i went on their computer, under Bria Stretto > preferences > security, and checked "always give access"

nevertheless, the employees have a "soket err connection refused", which i have never experienced on my end.

**Comment by CounterPathAPI** [comment]
If you are using Bria Stretto, did our admin set the attribute in the portal.  That overrides the user settings.  Can you send a log from one of those computers and post the log reference here?

**Comment by benoitfagot** [comment]
Hello, 

sorry for the trouble, I forgot that most of our employees work on TSEs and that was the reason they coudnt connect, they just had to open the browsers outside of TSE windows

thank you for your help
